### ISSUE TITLE
How to link libxml2 as a hunter package?

### ISSUE THREAD

**Issue by olliwang** [hunter-packages/libxml2-old#1]
I was trying to link `libxml2` as a hunter package. The doc page doesn't help (https://docs.hunter.sh/en/latest/packages/pkg/libxml2.html). So I tried the following code:

    hunter_add_package(libxml2)
    find_package(libxml2 CONFIG REQUIRED)
    target_link_libraries(app PRIVATE libxml2::libxml2)

However, this gave me the following error:

    Target "app" links to target "libxml2::libxml2" but the target was not
    found.  Perhaps a find_package() call is missing for an IMPORTED target, or
    an ALIAS target is missing?

**Comment by ruslo** [comment]
>  The doc page doesn't help

Well, there is nothing there, so I will be surprised if it will help somebody :)

You can find info in example:
* https://github.com/ruslo/hunter/blob/master/examples/libxml2/CMakeLists.txt

**Comment by olliwang** [comment]
Thanks. That's exactly what I'm looking for. Just a bit curious why this package uses different method than other hunter packages.

**Comment by ruslo** [comment]
> Just a bit curious why this package uses different method than other hunter packages.

Was added that way, it should be improved (documentation, example and package itself if needed) to use imported `foo::foo` kind of targets. Feel free to send pull requests.

**Comment by olliwang** [comment]
Got it. 👍
